language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_5609b0770c6e_key -iv $encrypted_5609b0770c6e_iv -in .config.json.enc -out .config.json -d
before_script:
  - npm install -g grunt-cli
  - npm install -g mocha
node_js:
  - "0.12"

